### ISSUE TITLE
Bug: iam.managed.policies is required

### ISSUE THREAD

**Issue by diranged** [keikoproj/iam-manager#65] opened 2020-12-18 16:12 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug Report

**What happened**:

The docs say that `iam.managed.policies` is optional. However, it seems required right now in the v0.0.6 release. If you leave it unset, you get these failures:

```
I1218 06:31:56.616501       1 event.go:281] Event(v1.ObjectReference{Kind:"Iamrole", Namespace:"iam-manager-system", Name:"iam-manager-iamrole-irsa", UID:"407b984d-8ce1-40e7-a342-071c1cd515b4", APIVersion:"iammanager.keikoproj.io/v1alpha1", ResourceVersion:"12755025", FieldPath:""}): type: 'Warning' reason: 'Error' Unable to create/update iam role due to error InvalidInput: ARN arn:aws:iam::xxx:policy/ is not valid.
```

**What you expected to happen**:

Simply no AttachRolePolicy IAM calls would be made if there was no default role configured in the configmap.

**Anything else we need to know?**:

Once I created a blank IAM Policy and configured it as the default iam.managed.policies setting, we were fine.

**Comment by mnkg561** [comment] 2020-12-18 17:32
Possible duplicate of https://github.com/keikoproj/iam-manager/issues/61

**Closed** 2021-01-25 18:46 UTC
Labels: bug
