### ISSUE TITLE
Feature Request: Customizable IAM Role Name Patterns

### ISSUE THREAD

**Issue by diranged** [keikoproj/iam-manager#62] opened 2020-12-18 16:01 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

This is a feature request. We plan to implement this ourselves in a PR and will share it back.

**What happened**:

The current naming pattern of `k8s-<resource-name>` or `k8s-<ns-name>` is extremely limited, and causes conflicts if you run multiple clusters. We should be able to customize not only the prefix, but the entire name pattern.

**What you expected to happen**:

Ideally we can set a property like `iam.role.prefix` to replace `k8s` with whatever we want. Additionally, `iam.role.pattern` should be created so that we can replace the entire role name, and use golang-based templating. Eg: `iam.role.pattern: {{ object.metadata.namespace}}-{{object.metadata.name}}-{{object.labels.foo }}`

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Anything else we need to know?**:

I am planning on working on this code change. I am wondering how active this project is? Will the PR be reviewed quickly and are you actively accepting code changes?

**Comment by mnkg561** [comment] 2020-12-18 17:28
@diranged Thanks for creating the issue/s. Yes, iam-manager is actively being used by us (Intuit) and feel free to create a PR. we will try to review the PR as soon as we can for sure.

**Comment by mnkg561** [comment] 2020-12-18 17:34
Possible duplicate of https://github.com/keikoproj/iam-manager/issues/47

**Closed** 2021-02-02 02:45 UTC
